# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/tests/tck-build-logic/src/main/resources/allowed-docker-images"
    assignees:
      - "jormundur00"
    schedule:
      interval: "daily"
