[versions]
# Project versions
nativeBuildTools = "0.9.14"

# External dependencies
junitPlatform = "1.8.1"
junitJupiter = "5.8.1"
groovy = "3.0.8"

[libraries]
nativeGradlePlugin = { module = "org.graalvm.buildtools:native-gradle-plugin", version.ref = "nativeBuildTools" }

# External dependencies
test-junit-platform-console = { module = "org.junit.platform:junit-platform-console", version.ref = "junitPlatform" }
test-junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }
test-junit-bom = { module = "org.junit:junit-bom", version.ref = "junitJupiter" }
test-junit-jupiter-core = { module = "org.junit.jupiter:junit-jupiter", version = "" }
test-junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version = "" }
test-junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version = "" }
test-junit-vintage = { module = "org.junit.vintage:junit-vintage-engine", version = "" }
