name: "Check code style"

on:
  push:
    paths:
      - '**.md'
      - 'library-and-framework-list*.json'
  pull_request:
    paths:
      - '**.md'
      - 'library-and-framework-list*.json'

jobs:
  build:
    name: "ðŸ“‹ Check style according to checkstyle.xml"
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
