name: "Check code style"

on:
  pull_request:
    paths-ignore:
      - 'docs/*'
      - '**.md'
      - 'library-and-framework-list*.json'

jobs:
  checkstyle:
    if: github.repository == 'oracle/graalvm-reachability-metadata'
    name: "ğŸ“‹ Check style according to checkstyle.xml"
    runs-on: "ubuntu-22.04"
    timeout-minutes: 15
    steps:
      - name: "â˜ï¸ Checkout repository"
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: "ğŸ”§ Prepare environment"
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew checkstyle
