name: "Check code style"

on:
  pull_request:

jobs:
  checkstyle:
    name: "ğŸ“‹ Check style according to checkstyle.xml"
    runs-on: "ubuntu-22.04"
    timeout-minutes: 15
    steps:
      - name: "â˜ï¸ Checkout repository"
        uses: actions/checkout@v4

      - name: "ğŸ” Detect relevant file changes"
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            relevant_files_changed:
              - '!docs/**'
              - '!**.md'
              - '!library-and-framework-list*.json'
          predicate-quantifier: 'every'

      - uses: actions/setup-python@v4
        if: steps.filter.outputs.relevant_files_changed == 'true'

      - name: "ğŸ”§ Setup java"
        if: steps.filter.outputs.relevant_files_changed == 'true'
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: "Run Checkstyle"
        if: steps.filter.outputs.relevant_files_changed == 'true'
        run: ./gradlew checkstyle
