name: "Scan docker images from the allowed docker images list"

on:
  # we should run this job if somebody wants to add/update allowed docker images
  pull_request:
    paths:
      - 'tests/tck-build-logic/src/main/resources/allowed-docker-images/**'
  # we should run this job once a week to check if new vulnerabilities are found in existing images
  schedule:
    - cron: "0 0 * * 6"

jobs:
  scan-images:
    name: "ğŸ” Scan docker images"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "â˜ï¸ Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Install required tools"
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
          sudo apt-get install jq
      - name: "ğŸ” Check changed docker images"
        if: github.event_name == 'pull_request'
        run: ./gradlew checkAllowedDockerImages --baseCommit=${{ github.event.pull_request.base.sha }} --newCommit=${{ github.event.pull_request.head.sha }}
      - name: "ğŸ” Check all docker images"
        if: github.event_name != 'pull_request'
        run: ./gradlew checkAllowedDockerImages
