name: "Scan docker images from the allowed docker images list"

on:
  # we run this job if somebody wants to add/update allowed docker images
  pull_request:

  # we run this job once a week to check if new vulnerabilities are found in existing images
  schedule:
    - cron: "0 0 * * 6"

jobs:
  detect-file-changes:
    name: "ğŸ” Detect relevant file changes"
    runs-on: "ubuntu-22.04"
    outputs:
      relevant-files-changed: ${{ steps.filter.outputs.relevant_files_changed }}
    steps:
      - name: "â˜ï¸ Checkout repository"
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4

      - name: "Check for relevant changes"
        id: filter
        if: github.event_name == 'pull_request'
        uses: dorny/paths-filter@v3
        with:
          filters: |
            relevant_files_changed:
              - 'tests/tck-build-logic/src/main/resources/allowed-docker-images/**'

  scan-images:
    name: "ğŸ” Scan docker images"
    runs-on: "ubuntu-22.04"
    needs: detect-file-changes
    if: github.event_name == 'schedule' || needs.detect-file-changes.outputs.relevant-files-changed == 'true'
    steps:
      - name: "â˜ï¸ Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install required tools"
        run: |
          curl -sSfL https://get.anchore.io/grype/v0.104.0/install.sh | sudo sh -s -- -b /usr/local/bin
          sudo apt-get install jq

      - name: "ğŸ” Check changed docker images"
        if: github.event_name == 'pull_request'
        run: ./gradlew checkAllowedDockerImages --baseCommit=${{ github.event.pull_request.base.sha }} --newCommit=${{ github.event.pull_request.head.sha }}

      - name: "ğŸ” Check all docker images"
        if: github.event_name == 'schedule' && github.repository == 'oracle/graalvm-reachability-metadata'
        run: ./gradlew checkAllowedDockerImages
