name: "Scan docker images from the allowed docker images list"

on:
  push:
    paths-ignore:
      - '**.md'
      - 'library-and-framework-list*.json'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'library-and-framework-list*.json'

jobs:
  scan-images:
    name: "ğŸ” Scan docker images"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "â˜ï¸ Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "ğŸ” Check docker images"
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
          sudo apt-get install jq
          ./gradlew checkAllowedDockerImages
