name: "Test changed metadata"

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'metadata/*'
      - 'tests/src/*'

jobs:
  get-changed-metadata:
    name: "ğŸ“‹ Get a list of all changed libraries"
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
  all-metadata-passed:
    name: "ğŸ§ª All metadata tests have passed"
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
